name: Bug Report
description: Report a bug or issue with Jobestry.
title: "[Bug]: "
labels: [ "bug", "triage" ]

body:
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior. Be as specific as possible.
        Include: which job site, what actions you took, what happened.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: dropdown
    id: desktop-os
    attributes:
      label: OS
      description: Select your operating system.
      options: [ Windows, macOS, Linux ]
      default: 0
    validations:
      required: true

  - type: dropdown
    id: desktop-browser
    attributes:
      label: Browser
      description: Select the browser where the issue occurs(Multiple choice).
      multiple: true
      options: [ Chrome, Opera, Opera GX, Firefox, Safari, Microsoft Edge, Brave ]
      default: 0
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Jobestry are you using?
      placeholder: 0.5.0

  - type: dropdown
    id: api-configured
    attributes:
      label: API Key Configured?
      description: Have you configured your Gemini API key?
      options: [ "Yes", "No", "Not sure" ]
      default: 0
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Check the browser console (F12) and paste any errors here.
      placeholder: Paste console errors here if any...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Provide additional details if necessary.
