import type { Config } from 'tailwindcss';

export default {
  theme: {
    extend: {
      colors: {
        brand: {
          50: 'var(--jobestry-brand-50)',
          100: 'var(--jobestry-brand-100)',
          200: 'var(--jobestry-brand-200)',
          300: 'var(--jobestry-brand-300)',
          400: 'var(--jobestry-brand-400)',
          500: 'var(--jobestry-brand-500)',
          600: 'var(--jobestry-brand-600)',
          700: 'var(--jobestry-brand-700)',
          800: 'var(--jobestry-brand-800)',
          900: 'var(--jobestry-brand-900)',
        },
        accent: {
          50: 'var(--jobestry-accent-50)',
          100: 'var(--jobestry-accent-100)',
          200: 'var(--jobestry-accent-200)',
          300: 'var(--jobestry-accent-300)',
          400: 'var(--jobestry-accent-400)',
          500: 'var(--jobestry-accent-500)',
          600: 'var(--jobestry-accent-600)',
          700: 'var(--jobestry-accent-700)',
          800: 'var(--jobestry-accent-800)',
          900: 'var(--jobestry-accent-900)',
        },
        success: {
          50: 'var(--jobestry-success-50)',
          100: 'var(--jobestry-success-100)',
          200: 'var(--jobestry-success-200)',
          300: 'var(--jobestry-success-300)',
          400: 'var(--jobestry-success-400)',
          500: 'var(--jobestry-success-500)',
          600: 'var(--jobestry-success-600)',
          700: 'var(--jobestry-success-700)',
          800: 'var(--jobestry-success-800)',
          900: 'var(--jobestry-success-900)',
        },
        warning: {
          50: 'var(--jobestry-warning-50)',
          100: 'var(--jobestry-warning-100)',
          200: 'var(--jobestry-warning-200)',
          300: 'var(--jobestry-warning-300)',
          400: 'var(--jobestry-warning-400)',
          500: 'var(--jobestry-warning-500)',
          600: 'var(--jobestry-warning-600)',
          700: 'var(--jobestry-warning-700)',
          800: 'var(--jobestry-warning-800)',
          900: 'var(--jobestry-warning-900)',
        },
        danger: {
          50: 'var(--jobestry-danger-50)',
          100: 'var(--jobestry-danger-100)',
          200: 'var(--jobestry-danger-200)',
          300: 'var(--jobestry-danger-300)',
          400: 'var(--jobestry-danger-400)',
          500: 'var(--jobestry-danger-500)',
          600: 'var(--jobestry-danger-600)',
          700: 'var(--jobestry-danger-700)',
          800: 'var(--jobestry-danger-800)',
          900: 'var(--jobestry-danger-900)',
        },
      },
      borderRadius: {
        sm: 'var(--jobestry-radius-sm)',
        md: 'var(--jobestry-radius-md)',
        lg: 'var(--jobestry-radius-lg)',
        xl: 'var(--jobestry-radius-xl)',
        '2xl': 'var(--jobestry-radius-2xl)',
        full: 'var(--jobestry-radius-full)',
      },
      boxShadow: {
        sm: 'var(--jobestry-shadow-sm)',
        md: 'var(--jobestry-shadow-md)',
        lg: 'var(--jobestry-shadow-lg)',
        xl: 'var(--jobestry-shadow-xl)',
        '2xl': 'var(--jobestry-shadow-2xl)',
        inner: 'var(--jobestry-shadow-inner)',
        focus: 'var(--jobestry-focus-ring)',
        'focus-success': 'var(--jobestry-focus-ring-success)',
        'focus-error': 'var(--jobestry-focus-ring-error)',
      },
      transitionTimingFunction: {
        fast: 'cubic-bezier(0.4, 0, 0.2, 1)',
        normal: 'cubic-bezier(0.4, 0, 0.2, 1)',
        slow: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '200ms',
        slow: '300ms',
      },
      spacing: {
        '4.5': '1.125rem',
        '13': '3.25rem',
        '15': '3.75rem',
        '18': '4.5rem',
        '22': '5.5rem',
      },
      minWidth: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      minHeight: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      animation: {
        'fade-in': 'fade-in var(--jobestry-transition-normal) ease-out',
        'fade-in-up': 'fade-in-up var(--jobestry-transition-normal) ease-out',
        'fade-in-down': 'fade-in-down var(--jobestry-transition-normal) ease-out',
        'scale-in': 'scale-in var(--jobestry-transition-normal) ease-out',
        'slide-in-right': 'slide-in-right var(--jobestry-transition-normal) ease-out',
        'pulse-ring': 'pulse-ring 2s infinite',
        'spin-slow': 'spin 1.5s linear infinite',
      },
    },
  },
  plugins: [],
} as Omit<Config, 'content'>;
